### ISSUE TITLE
Some general Questions

### ISSUE THREAD

**Issue by DriftingPig** [rainwoodman/fastpm#32]
Hello,
I have a few more questions. 

First, what the the unit for the timestep perimeter? (In the *.lua file, time_step = linspace(0.1, 1, 10))

Second, for the box size, is it able to define it as a 3-Vector? Or I can only define a cubic box?

Third, is the 'linear_density_redshift' in *.lua file the input redshift, and 'output_redshifts' are the output redshift? If linear_density_redshift is smaller than output_redshifts, does it mean the system need to go backwards in time?

Thanks,
Hui

**Comment by rainwoodman** [comment]
It is in scaling factor.

Currently it is only a cubic box. I think the underlying code supports anisotropic box, but the FastPMSolver interface doesn't expose this.

`linear_density_redshift` is the redshift to which the linear input power spectrum file is normalized -- basically the code we rescale the input power spectrum back to z=0 according to its cosmology (matter only) before starting the traditional n-body simulation stuff (scaling to initial redshift, 2lpt then pm). It has nothing to do with the evolution, backward or forward.

I've never tried to run the code backward -- I don't think it works -- because the ordering of k-d-f operators needs to be tweaked to walk backward correctly.
